### ISSUE TITLE
Some projects make the robot service automatically shut itself off

### ISSUE THREAD

**Issue by cecilialau6776** [kauailabs/allwpilib#17] opened 2019-08-07 00:21 UTC
I have examples of working projects on my github. I'm not sure what causes this to happen.

**Comment by kauailabs** [comment] 2019-08-12 19:04
Can you please double check the projects on your github?  When I download this, I'm seeing two folders (NSP-PI, NSP-PI2) but they're empty.

Also, if logs are available that'd be great; it's not clear exactly how the symptoms (robot service automatically shut itself off) translate into.  

We have seen a problem when using Talons in Java that the robot app just freezes after initialization, the latest update to Phoenix-vmx.json resolves that, is it possible that this is what is being referred to?

**Comment by cecilialau6776** [comment] 2019-08-12 19:22
I'm unsure. I'll double-check the projects once I get a chance.

**Comment by kauailabs** [comment] 2019-08-27 20:15
We're trying to reproduce this, and have found an issue that only occurs with robot applications that use the "TimedRobot" base class; this issue doesn't occur when using the "IterativeRobot" base class.  Could you please try these with IterativeRobot and see if the issue disappears?  This information will help us determine if we understand the root cause of the issue you are seeing.

**Comment by kauailabs** [comment] 2019-09-01 23:56
@PixelGaMERCaT, please retest this w/VMX-pi 2019.4.1 Beta Release 13.

**Comment by kauailabs** [comment] 2019-09-17 19:00
Similar to Issue#22, this scenario can be caused due to a conflict in signal handling with the java vm.  We will have a new Hal library available soon with the fix for this.

**Comment by kauailabs** [comment] 2019-09-23 23:42
This is fixed as of 2019.4.1 VMXpi Beta 16 Candidate (released 9/22/2019) and vmx-pi HAL version 1.1.207.

**Closed as completed by kauailabs** 2019-09-23 23:42 UTC
